# Numpy

In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [3]:
print(type(a))pri

<class 'numpy.ndarray'>


In [4]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [10]:
L= range(1000)
%timeit [i**2 for i in L]

618 µs ± 12.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [12]:
A=np.arange(1000) # numpy provides  faster numerical operations and are memory efficient
%timeit A**2

4.22 µs ± 536 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [15]:
b=np.array([1,4,3,6])
print(b)

[1 4 3 6]


In [21]:
b.ndim
b.shape

(4,)

In [ ]:
# 2-D and 3-D Arrays

In [25]:
c= np.array([[1,2,3,],[4,5,6,]])
print(c)

[[1 2 3]
 [4 5 6]]


In [26]:
c.ndim

2

In [27]:
c.shape

(2, 3)

In [29]:
len(c)

2

In [32]:
d=np.array([[[1,2,3],[4,5,6]],[[8,9,11],[12,13,14]]])
print(d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 8  9 11]
  [12 13 14]]]


In [33]:
d.ndim

3

In [34]:
d.shape

(2, 2, 3)

In [35]:
len(d)

2

In [36]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [39]:
b=np.arange(1,10,2) #start, end (exclusive), step
print(b)

[1 3 5 7 9]


In [43]:
f=np.linspace(0,1,6)
print(f)

[0.  0.2 0.4 0.6 0.8 1. ]


In [44]:
g=np.ones((3,3))
print(g)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [48]:
g=np.zeros((3,3))
print(g)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# Identity Matrix

In [50]:
# Diagonal elements are always equal to one and all the other non-diagonal elements are zeros
a=np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [51]:
np.eye(3,2)

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [54]:
#constructing diagonal array- creating array using the diag function
a=np.diag([1,2,4,5])
print(a)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 4 0]
 [0 0 0 5]]


In [55]:
# creating arrays using random numbers (a.k.a uniform distributed random number)
b=np.random.rand(4)
print(b)

[0.73313334 0.16063861 0.04966004 0.54077763]


In [58]:
a=np.random.randn(4) #standard normal variate/goshen
print(a)
#check a chapter on probability and statistics to understand more about the types of random distributions

[-0.76769884 -0.72378291 -1.57772247 -0.39000213]


In [63]:
#Basic Data type of Numpy
a=np.arange(10)
print(a)
a.dtype

[0 1 2 3 4 5 6 7 8 9]


dtype('int32')

In [64]:
b=np.arange(10,dtype='float32')
print(b)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [66]:
d=np.array([1+2j, 2+3j]) #complex datatype
d.dtype

dtype('complex128')

In [68]:
e=np.array([False,True,False,True])
e.dtype

dtype('bool')

In [77]:
m=np.array(['Ken','Shalon', 'Alex'])
m.dtype

dtype('<U6')

In [80]:
# indexing and slicing in numpy array
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [83]:
print(a[5])

5


In [90]:
a=np.diag([1,2,3,4])
print(a)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [94]:
a[2,3]=7 # assigning values

In [95]:
print(a)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 7]
 [0 0 0 4]]


In [96]:
print(a[3,3])

4


In [97]:
# slicing in numpy

In [101]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [102]:
a[1:8:2]

array([1, 3, 5, 7])

In [103]:
b=np.arange(10)
b[5:]

array([5, 6, 7, 8, 9])

In [105]:
b[5:]=10
print(b)

[ 0  1  2  3  4 10 10 10 10 10]


In [120]:
c=np.arange(5) # reverse array
b[5:]=c[::-1]
b

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

In [123]:
# copies and views
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [124]:
b=a[::2]

In [126]:
b


array([0, 2, 4, 6, 8])

In [128]:
np.shares_memory(a,b)

True

In [129]:
b[0]=10 # if you modify b, a will also get modified
b

array([10,  2,  4,  6,  8])

In [131]:
a

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [133]:
# forcing a copy ; so that if you change one array, the other doesn't get changed
c=a[::3].copy()
c

array([10,  3,  6,  9])

In [134]:
c[0]=2
c

array([2, 3, 6, 9])

In [135]:
a

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [137]:
b

array([10,  2,  4,  6,  8])

In [138]:
np.shares_memory(b,c)

False

In [151]:
# fancy indexing (Boolean Masks)
a=np.random.randint(0,20,15)
a

array([18,  3,  2, 19, 16, 10,  1, 17, 17, 17,  4,  5,  7, 11,  8])

In [152]:
mask=(a%2==0)# masks create copies and not views

In [153]:
extract_from_a=a[mask]

In [154]:
extract_from_a

array([18,  2, 16, 10,  4,  8])

In [157]:
a[mask]=-1
a

array([-1,  3, -1, 19, -1, -1,  1, 17, 17, 17, -1,  5,  7, 11, -1])

In [158]:
a=np.arange(0,100,10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [159]:
a[[2,3,2,4,2]]

array([20, 30, 20, 40, 20])

In [160]:
a[[7,9]]=-200
a

array([   0,   10,   20,   30,   40,   50,   60, -200,   80, -200])

# Numerical Operations in Numpy

In [162]:
a=np.array([1,2,3,4]) #scalar radiation
a+1

array([2, 3, 4, 5])

In [163]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

In [164]:
#All arithmetic operates elementwise

In [165]:
b=np.ones(4)+1
a-b

array([-1.,  0.,  1.,  2.])

In [167]:
a*b

array([2., 4., 6., 8.])

In [169]:
#Matrix multiplication
c=np.diag([1,2,3,4])

In [171]:
print(c*c)
print("*************************")
print(c.dot(c))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
*************************
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [174]:
a=np.array([1,2,3,4])
b=np.array([5,2,7,4])
a==b

array([False,  True, False,  True])

In [175]:
type(a==b)

numpy.ndarray

In [176]:
a>b

array([False, False, False, False])

In [182]:
# arraywise comparisons
a=np.array([1,2,3,5])
b=np.array([4,3,5,6])
c=np.array([1,2,3,5])
np.array_equal(a,b)

False

In [183]:
np.array_equal(a,c)

True

In [184]:
#logical operators
a=np.array([1,1,0,0],dtype=bool)
b=np.array([1,0,1,0],dtype=bool)
np.logical_or(a,b)

array([ True,  True,  True, False])

In [185]:
np.logical_and(a,b)

array([ True, False, False, False])

In [186]:
a=np.arange(5)
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [188]:
np.log(a)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_7108\176755284.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [190]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

# Shape Mismatch

In [192]:
a=np.array([1,2,3,4]) # operations can't happen as the arrays are not of the same sizes
b=np.array([2,3])
a+b

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

# Basic Reductions

In [194]:
# computing sums
a=np.array([1,2,3,4])
np.sum(a)

10

In [196]:
x=np.array([[1,1],[2,2]])
x


array([[1, 1],
       [2, 2]])

In [197]:
x.sum(axis=0) # column first dimension

array([3, 3])

In [199]:
x.sum(axis=1) # row first dimension

array([2, 4])

# Other reductions

In [201]:
a=np.array([1,2,3,4])
min(a)

1

In [203]:
max(a)

4

In [204]:
np.argmin(a) #index of the min element

0

In [205]:
np.argmax(a) #index of the max element

3

# Logical Operators

In [206]:
np.all([True,True,True])

True

In [207]:
np.all([True,False,True])

False

In [209]:
np.all([False,False,False])

False

In [210]:
np.any([True,False,False])

True

In [211]:
np.any([False,True])

True

In [215]:
a=np.zeros([50,50])
np.any(a:=0)

False

In [216]:
np.all(a==a)

True

In [217]:
a=np.array([1,2,3,2])
b=np.array([2,2,3,2])
c=np.array([6,4,4,5])
((a<=b)&(b<=c)).all()

True

# Statistics

In [227]:
x=np.array([1,2,3,1])
y=np.array([[1,2,3],[5,6,7]])
np.mean(x)

1.75

In [228]:
np.mean(y)

4.0

In [229]:
np.median(x)

1.5

In [234]:
np.median(y,axis=1) #last axis

array([2., 6.])

In [235]:
x.std()

0.82915619758885

In [237]:
# data=np.loadtxt("population") loading data into numpy

In [239]:
a.T

array([1, 2, 3, 2])

# Broadcasting

In [251]:
a=np.tile(np.arange(0,40,10),(3,1))
print(a)
a=a.T
print(a)

[[ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]]
[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]


In [253]:
b=np.array([0,1,2])
b

array([0, 1, 2])

In [254]:
a+b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [257]:
a=np.arange(0,40,10)
a.shape

(4,)

In [259]:
a=a[:,np.newaxis] #adding new axis -> 2D array
a.shape

(4, 1)

In [260]:
a+b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

# Array Shape Manipulation

In [261]:
## Flattening
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [262]:
a.shape

(2, 3)

In [264]:
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [266]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [267]:
a.T.ravel()

array([1, 4, 2, 5, 3, 6])

# Reshaping

In [268]:
print(a.shape)
print(a)

(2, 3)
[[1 2 3]
 [4 5 6]]


In [271]:
b=a.ravel()
b

array([1, 2, 3, 4, 5, 6])

In [272]:
b=b.reshape([2,3])

In [273]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [274]:
b[0,0]=100
a

array([[100,   2,   3],
       [  4,   5,   6]])

In [277]:
a=np.zeros([3,2])
b=a.T.reshape(3*2)
b[0]=50
a

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

# Adding dimensions

In [285]:
z=np.array([1,2,3])
z [:,np.newaxis]

array([[1],
       [2],
       [3]])

In [286]:
z

array([1, 2, 3])

In [287]:
a=np.arange(4*3*2).reshape(4,3,2)
a.shape

(4, 3, 2)

In [288]:
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [290]:
a[0,2,1]

5

# Resizing

In [295]:
a=np.arange(4)

In [297]:
a.resize((8,))
a

array([0, 1, 2, 3, 0, 0, 0, 0])

# Sorting

In [299]:
# sorting along axis
a=np.array([[5,4,6],[2,3,2]])
b=np.sort(a,axis=1)
b

array([[4, 5, 6],
       [2, 2, 3]])

In [300]:
# in place sorting
a.sort(axis=1)
a

array([[4, 5, 6],
       [2, 2, 3]])

In [301]:
#sorting with fancy indexing
a=np.array([4,3,1,2])
j=np.argsort(a)
j


array([2, 3, 1, 0], dtype=int64)

In [303]:
a[j]

array([1, 2, 3, 4])

# Operators

In [306]:
# floor division/operator
15//2

7

In [310]:
-15//2

-8

In [313]:
# modulus operator
15%2

1

In [316]:
2%2

0

In [318]:
#exponent operator
2**2

4

In [336]:
# other arithmetic operators include +, /, -, *

# Comparison Operators

In [321]:
# >, <, =, !=,=<, >=

In [323]:
# example

2!=3

True

In [332]:
2>3

False

# Logical Operators

In [333]:
# and, or not

In [334]:
# And
# True and True is True
# True and False is False
#False and True is False
#False and False is False

In [335]:
# OR
# True or True is True
#True orf False is True
# False or True is True
# False or False is False

# Bitwise Operator

In [337]:
# &,|, ~, ^, >>, <<

In [338]:
# Bitwise And (&)
a,b = 10,4
print(a&b)

0


In [340]:
# Bitwise Or (|)

print(a|b)

14


# Assignment Operators

In [341]:
# =, +=, -=, *=, /=, %=, //=, **=,|=,^=, >>=, <<=


In [351]:
a=10
a+=20
print(a)

30


In [352]:
a*=10
print(a)


300


In [356]:
a/=2
print(a)

18.75


In [357]:
a**=2
print(a)

351.5625


# Special Operators

In [ ]:
# Identity operators (is and is not)
a,b = 5,5

print(a is b)

In [360]:
print(a is not b)

False


In [364]:
l1=[1,2,3]
l2=[1,2,3]

print(l1 is l2)

False


In [365]:
s1='AAIC'
s2='AAIC'
print(s1 is not s2)

False


# Membership Operators

In [368]:
# in and not in
lst = [1,2,3,4]
print( 1 in lst )

True


In [369]:
d={1:"a", 2:"b"} # this is a dictionary
print(1 in d)

True


# Control Statements - if................elif..................else

In [373]:
# example
num=-1

if num>10:
        print("Number is greater than 10")
print("This will print always")
        

This will print always


In [374]:
# note that 0, none and false are taken to be false; anything else is true


# if else

In [377]:
num = -2
if num >=0:
    print("It is a positive number")
else:
    print("It is a negative number")
print("This statement will always be printed")

It is a negative number
This statement will always be printed


# elif

In [379]:
num = -2

if num>10:
    print("positive number")
elif n==0:
    print("zero")
else:
    print("negative number")

negative number


# Nested if Statements

In [394]:
num = -2
if num >= 0:
    if num==0:
        print ("zero")
    else:
        print("positive number")
else:
    print("negative number")
    

negative number


# Python while loop

In [4]:
# Example: Find the product of all values in a list

lst = [10,20,30,40,60]

Product = 1
index = 0

while index < len(lst):
    Product *= lst[index]
    index +=1
print("Product is: {}".format(Product))

Product is: 14400000


In [13]:
# Example 2:
numbers = [1,2,3,4,5,6,7]
# iterating over the list
index = 0

while index < len(numbers):
    print(numbers[index])
    index +=1
else:
    print("no item is left on the list")

1
2
3
4
5
6
7
no item is left on the list


# Python for loop

In [15]:
# Example : product for all numbers in a list
lst = [10,20,30,40, 50]
product = 1
for elm in lst:
    product *= elm
print("product is{}".format(product))

product is12000000


# Range in Python

In [17]:
# print range of 10
for i in range (10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [24]:
for i in range(0,20,5):
    print(i)

0
5
10
15


In [30]:
lst= ['Ruth','Jane','Judy','Lucy','Ann']
# iterate over the list using index
for index in range (len(lst)):
    print(lst[index])

Ruth
Jane
Judy
Lucy
Ann


In [31]:
numbers = [1,2,3,4]
for item in numbers:
    print(item)
else:
    print("no item is left in the list")

1
2
3
4
no item is left in the list


# Control Flow: Break and Continue

In [1]:
numbers = [1,2,3,4]
for num in numbers:
    if num == 4:
        break
    print(num)
else:
    print( "in the else block")
print ("outside for loop")

1
2
3
outside for loop


In [14]:
num= int(input("Enter a number:"))
isDivisible = False;

i=2;
while i <num:
    if num%i == 0:
        isDivisible=True;
        print ("{} is divisible by {}".format(num,i))
        break
    i+=1
if isDivisible:
    print("{}is not a prime number".format(num))
else:
    print("{} is a prime number".format(num))

Enter a number:16
16 is divisible by 2
16is not a prime number


In [18]:
# Continue statement
# Example: print all odd numbers
numbers =[1,2,3,4,5]
for num in numbers:
    if num%2==0:
        continue
    print(num)
else:
    print("else block")

1
3
5
else block


In [22]:
index1 = 10
index2 = 50

print("print prime numbers between {0} and {1} are:".format(index1, index2))


for num in range (index1, index2+1):
    if num >1:
        isDivisible= False;
        for index in range (2,num):
            if num % index ==0:
                isDivisible=True;
            if not isDivisible:
                print(num);


print prime numbers between 10 and 50 are:
11
11
11
11
11
11
11
11
11
13
13
13
13
13
13
13
13
13
13
13
15
17
17
17
17
17
17
17
17
17
17
17
17
17
17
17
19
19
19
19
19
19
19
19
19
19
19
19
19
19
19
19
19
21
23
23
23
23
23
23
23
23
23
23
23
23
23
23
23
23
23
23
23
23
23
25
25
25
27
29
29
29
29
29
29
29
29
29
29
29
29
29
29
29
29
29
29
29
29
29
29
29
29
29
29
29
31
31
31
31
31
31
31
31
31
31
31
31
31
31
31
31
31
31
31
31
31
31
31
31
31
31
31
31
31
33
35
35
35
37
37
37
37
37
37
37
37
37
37
37
37
37
37
37
37
37
37
37
37
37
37
37
37
37
37
37
37
37
37
37
37
37
37
37
39
41
41
41
41
41
41
41
41
41
41
41
41
41
41
41
41
41
41
41
41
41
41
41
41
41
41
41
41
41
41
41
41
41
41
41
41
41
41
41
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
43
45
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
47
49
49
49
49
49
